services:
  rest-api-postgres:
    image: postgres:13
    container_name: rest-api-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "7285:5432"