spring:
  application:
    name: RestApi
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    postgres:
      url: jdbc:postgresql://localhost:7285/postgres
      username: postgres
      password: ${POSTGRES_PASSWORD}
    h2:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
      username: h2
      password: ${H2_PASSWORD}
  h2:
    console:
      enabled: true
      path: /h2
  cloud:
    function:
      definition: reportPositions|retrievePositions
    stream:
      poller:
        fixed-delay: 10000
      bindings:
        reportPositions-out-0:
          destination: aircraftpositions
        retrievePositions-in-0:
          destination: aircraftpositions
          group: aircraftpositions
management:
  endpoints:
    web:
      exposure:
        include: beans, configprops, env, health, loggers, mappings, metrics
  endpoint:
    health:
      show-details: ALWAYS
greeting:
  name: Dakota
  coffee: ${greeting.name} is drinking Café Cereza
droid:
  id: BB-8
  description: Small, rolling android. Probably doesn't drink coffee.