spring:
  application:
    name: RestApi
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:7285/postgres
    username: postgres
    password: ${POSTGRES_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: beans, configprops, env, health, loggers, mappings, metrics
greeting:
  name: Dakota
  coffee: ${greeting.name} is drinking Café Cereza
droid:
  id: BB-8
  description: Small, rolling android. Probably doesn't drink coffee.